### ISSUE TITLE
This sounds like a 7mm gun [sic]

### ISSUE THREAD

**Issue by enormandeau** [sudasana/armcom#2]
When crew mate reports on enemy guns, the caliber is badly reported. Only the first digit of the full caliber is printed out. For example 7mm instead of 75mm and 8mm instead of 88mm.
I thought I had fixed this in 1.04. Maybe player is using old version?

**Comment by sudasana** [comment]
It should be fine now - the relevant code is:

```
 gun_type = self.stats['main_gun']
...
 CrewTalk('That sounded like a ' + gun_type[:2] + 'mm gun!')
```

Perhaps earlier the string slice had been [:1]?

**Comment by enormandeau** [comment]
I remember I did change it from `[:1]` to `[:2]`.
