### ISSUE TITLE
Crash if firing WB or HCBI when maintaining RoF

### ISSUE THREAD

**Issue by fa-de** [sudasana/armcom#6]
When doing the RoF check in line 8107, the code references the variable stop_firing, which seems to be only assigned in line 7991 (inside the else of 'if tank.ammo_load in ['WP', 'HCBI']:')
Therefore, when firing one of these ammunition types, and `roll <= tank.stats['rof_num']` is true, the code references the unassigned variable stop_firing and crashes.

Proposed fix: Assign stop_firing = False somwhere above the if in line 7947

**Comment by sudasana** [comment]
Have made the requested change, thanks for the find!
